
export component DragArea inherits TouchArea {
    width: 100%;
    height: 100%;
    mouse-cursor: pointer;

    property <bool> drag-pressed: false;
    property <length> drag-start-x: 0;
    property <length> drag-start-y: 0;

    callback on-move-window(length, length);

    moved => {
        if (drag-pressed) {
            on-move-window(self.mouse-x - drag-start-x, self.mouse-y - drag-start-y);
        }
    }

    pointer-event(ev) => {
        if (ev.button == PointerEventButton.left) {
            if (ev.kind == PointerEventKind.down) {
                drag-pressed = true;
                drag-start-x = self.mouse-x;
                drag-start-y = self.mouse-y;
            } else if (ev.kind == PointerEventKind.up) {
                drag-pressed = false;
            }
        }
    }
}
