import { Button } from "std-widgets.slint";
import { IconButton } from "components/icon_button.slint";
import { DragArea } from "components/drag_area.slint";
import { Background } from "components/background.slint";

export component AppWindow inherits Window {
    height: 500px;
    width: 800px;

    no-frame: true;
    background: transparent;

    callback move-window(length, length);
    callback close_window();
    callback minimize_window();

    DragArea {
        on-move-window(offset-x, offset-y) => {
            move-window(offset-x, offset-y);
        }
    }
    
    Background {}

    VerticalLayout {
        HorizontalLayout {
            height: 50px;
            spacing: 24px;
            padding: 14px;
            alignment: end;
            IconButton {
                icon: @image-url("assets/icons/minimize.svg");
                background: transparent;
                color: whitesmoke;
                clicked => {
                    debug("最小化按钮被点击");
                    minimize_window();
                }
            }
            IconButton {
                icon: @image-url("assets/icons/close.svg");
                background: transparent;
                color: whitesmoke;
                clicked => { 
                    debug("关闭按钮被点击"); 
                    close_window()
                }
            }
        }
    }
}
