import { Button } from "std-widgets.slint";
import { IconButton } from "components/icon_button.slint";
import { DragArea } from "components/drag_area.slint";
import { Background } from "components/background.slint";
import { TitleBar } from "components/titlebar.slint";

export component AppWindow inherits Window {
    height: 500px;
    width: 800px;

    no-frame: true;
    background: transparent;

    callback move-window(length, length);
    callback close_window();
    callback minimize_window();

    DragArea {
        on-move-window(offset-x, offset-y) => {
            move-window(offset-x, offset-y);
        }
    }
    
    TitleBar {
        close_window => {
            close_window();
        }
        minimize_window => {
            minimize_window();
        }
    }

    Background {}
}
