name: Build and Release

on:
  push:
    branches: [ "**" ]
    tags: [ "v*" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Handle gettext (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew unlink gettext && brew link --force gettext || true
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'
        
    - name: Install UV (Windows)
      if: matrix.os == 'windows-latest'
      run: pip install uv
    
    - name: Install UV (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        source $HOME/.cargo/env
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Verify UV installation
      run: uv --version
    
    - name: Fix pyproject.toml authors field
      if: matrix.os == 'ubuntu-latest'
      run: |
        # Backup original file
        cp pyproject.toml pyproject.toml.backup
        # Fix authors field to be an array
        sed -i 's/authors = "hmr-BH and contributors"/authors = [{name = "hmr-BH and contributors"}]/' pyproject.toml
    
    - name: Install project dependencies
      run: uv sync --no-dev
    
    - name: Restore original pyproject.toml
      if: matrix.os == 'ubuntu-latest'
      run: |
        mv pyproject.toml.backup pyproject.toml
    
    - name: Install Ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y libgl1-mesa-dri mesa-common-dev libglu1-mesa
        sudo apt-get install -y libglib2.0-0
        sudo apt-get install -y upx
    
    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: brew install upx
    
    - name: Install Windows dependencies
      if: matrix.os == 'windows-latest'
      run: |
        uv pip install cmake ninja
    
    - name: Create build config
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          echo '{"visual_studio": {"vcvars64_path": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"}, "cmake": {"executable_path": "cmake"}, "build": {"parallel_jobs": 4}}' > build_config.json
        else
          echo '{"cmake": {"executable_path": "cmake"}, "build": {"parallel_jobs": 4}}' > build_config.json
        fi
      shell: bash
    
    - name: Build project
      run: uv run python scripts/build.py
    
    - name: Package artifacts
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          mv dist/amcl dist/AMCL-Windows-x64
        elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          mv dist/amcl dist/AMCL-Linux-x64
        elif [ "${{ matrix.os }}" = "macos-latest" ]; then
          mv dist/amcl dist/AMCL-macOS-x64
        fi
    
    - name: Upload Release Assets
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/AMCL-Windows-x64/**
          dist/AMCL-Linux-x64/**
          dist/AMCL-macOS-x64/**
        draft: false
        prerelease: false
        generate_release_notes: true
