name: Build Application

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.12', '3.11', '3.10']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install CMake
      uses: lukka/get-cmake@latest
      with:
        version: "3.30.0"

    - name: Install system dependencies
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libnotify-dev libsecret-1-dev
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew update
          brew install pkg-config
        fi
      shell: bash

    - name: Install vcpkg and dependencies (Windows only)
      if: matrix.os == 'windows-latest'
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
        ./vcpkg/vcpkg install unofficial-wintoast
      shell: bash
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka PySide6
        
    - name: Build with Nuitka
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          python -m nuitka -oAMCL --standalone --lto=yes --disable-ccache --include-data-dir=amcl/assets=assets --enable-plugin=pyside6 --jobs=2 --output-dir=build --remove-output --assume-yes-for-downloads --mingw64 --windows-console-mode=disable amcl/src/amcl.py
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          python -m nuitka -oAMCL --standalone --lto=yes --disable-ccache --include-data-dir=amcl/assets=assets --enable-plugin=pyside6 --jobs=2 --output-dir=build --remove-output --assume-yes-for-downloads --macos-create-app-bundle amcl/src/amcl.py
        else
          python -m nuitka -oAMCL --standalone --lto=yes --disable-ccache --include-data-dir=amcl/assets=assets --enable-plugin=pyside6 --jobs=2 --output-dir=build --remove-output --assume-yes-for-downloads amcl/src/amcl.py
        fi
      shell: bash
        
    - name: Setup MSVC on Windows
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1
      
    - name: Build launcher
      run: |
        mkdir -p launcher/build
        cd launcher/build
        
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../../vcpkg/scripts/buildsystems/vcpkg.cmake
        else
          # Linux 和 macOS 构建
          cmake ..
        fi
        
        cmake --build . --config Release -j 2
      shell: bash
        
    - name: Package artifacts
      run: |
        mkdir -p dist
        if [ -d "build" ]; then
          mv build dist/amcl
        fi
        
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          mkdir -p dist/launcher
          cp launcher/build/Release/AMCL.exe dist/launcher/ 2>/dev/null || cp launcher/build/AMCL dist/launcher/
        else
          mkdir -p dist/launcher
          cp launcher/build/AMCL dist/launcher/
        fi
      shell: bash
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-python${{ matrix.python-version }}
        path: dist/
